version: '3'
services:
  odoo:
    image: odoo:18
    environment:
      - HOST=odoo-db
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
    depends_on:
      - odoo-db
  odoo-db:
    image: postgres:13
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
volumes:
  odoo-data:
  odoo-db-data:
