services:
  db:
    container_name: db
    image: postgres:13
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"   # <-- expose Postgres to host


  odoo:
    container_name: odoo
    image: odoo:18
    environment:
      - DB_HOST=db
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_PORT=5432
      - ADDONS_PATH=/mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
    ports:
      - "8069:8069"
    volumes:
      - ./odoo-custom-addons:/mnt/extra-addons    # <-- mount your local folder
      - odoo-data:/var/lib/odoo
    depends_on:
      - db

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin-data:/var/lib/pgadmin


volumes:
  odoo-data:
  db-data:
  pgadmin-data:
