# Use the official .NET SDK image
FROM mcr.microsoft.com/dotnet/sdk:7.0

# Set working directory inside the container
WORKDIR /app

# Start a bash shell by default for interactive development
CMD ["/bin/bash"]
